// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl1CxBLo3s-gkGumaml5ExnRL7F5BsZnA',
    appId: '1:596278953789:web:d10b1e7f6095ff07e72754',
    messagingSenderId: '596278953789',
    projectId: 'chat-app-2a2ce',
    authDomain: 'chat-app-2a2ce.firebaseapp.com',
    storageBucket: 'chat-app-2a2ce.appspot.com',
    measurementId: 'G-DFJFS0D19V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWjMQFxMZQ-rglrCrXUNLtPApmqNVQIk4',
    appId: '1:596278953789:android:6d3f42b46816e6bee72754',
    messagingSenderId: '596278953789',
    projectId: 'chat-app-2a2ce',
    storageBucket: 'chat-app-2a2ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLtC_9c1iXxKbQeY7c60i4LyMgURNfgxk',
    appId: '1:596278953789:ios:fa52bb1186b96f27e72754',
    messagingSenderId: '596278953789',
    projectId: 'chat-app-2a2ce',
    storageBucket: 'chat-app-2a2ce.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLtC_9c1iXxKbQeY7c60i4LyMgURNfgxk',
    appId: '1:596278953789:ios:fa52bb1186b96f27e72754',
    messagingSenderId: '596278953789',
    projectId: 'chat-app-2a2ce',
    storageBucket: 'chat-app-2a2ce.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl1CxBLo3s-gkGumaml5ExnRL7F5BsZnA',
    appId: '1:596278953789:web:c6f214eca88c323fe72754',
    messagingSenderId: '596278953789',
    projectId: 'chat-app-2a2ce',
    authDomain: 'chat-app-2a2ce.firebaseapp.com',
    storageBucket: 'chat-app-2a2ce.appspot.com',
    measurementId: 'G-HN6NXF5L7T',
  );
}
